DATA:
  TASK_TYPE: 'graph_regression'
  DATASET: zinc-subset
  SOURCE: pyg
  NUM_ATOMS: 50
  NUM_EDGES: 50
  NUM_SPATIAL: 50
  MULTI_HOP_MAX_DIST: 5
  NUM_EDGE_DIST: 5
  NUM_IN_DEGREE: 50
  NUM_OUT_DEGREE: 50
  BATCH_SIZE: 256 # 256 * 1 * 1 = 256
MODEL:
  TYPE: GPTrans
  DROP_PATH_RATE: 0.3
  DROP_RATE: 0.3
  ATTN_DROP_RATE: 0.5
  GPTRANS:
    NUM_LAYERS: 12
    NUM_HEADS: 8
    NODE_DIM: 80
    EDGE_DIM: 40
    LAYER_SCALE: 1.0
    MLP_RATIO: 1.0
TRAIN:
  EMA:
    ENABLE: True
    DECAY: 0.9998
  BASE_LR: 10e-4 # actual lr is 5e-4
  MIN_LR: 1e-9
  OPTIMIZER:
    NAME: fused_adamw
  EPOCHS: 10000
  WARMUP_EPOCHS: 600
  WEIGHT_DECAY: 0.05
EVAL_FREQ: 10
SAVE_FREQ: 10