DATA:
  TASK_TYPE: 'node_classification'
  DATASET: cluster
  SOURCE: pyg
  NUM_ATOMS: 2563
  NUM_EDGES: 1537
  NUM_SPATIAL: 5
  MULTI_HOP_MAX_DIST: 5
  NUM_EDGE_DIST: 5
  NUM_IN_DEGREE: 100
  NUM_OUT_DEGREE: 100
  BATCH_SIZE: 32 # 32 * 1 * 8 = 256
  METRIC: 'Accuracy'
MODEL:
  TYPE: GPTrans
  DROP_PATH_RATE: 0.3
  DROP_RATE: 0.3
  ATTN_DROP_RATE: 0.5
  GPTRANS:
    NUM_LAYERS: 12
    NUM_HEADS: 8
    NODE_DIM: 80
    EDGE_DIM: 40
    LAYER_SCALE: None
    MLP_RATIO: 1.0
    NUM_CLASSES: 6
TRAIN:
  EMA:
    ENABLE: True
    DECAY: 0.999
  BASE_LR: 10e-4 # actual lr is 32 * 8 / 512 * 10e-4 = 5e-4
  MIN_LR: 1e-9
  OPTIMIZER:
    NAME: fused_adamw
  EPOCHS: 1000
  WEIGHT_DECAY: 0.05
  USE_CHECKPOINT: True
  ACCUMULATION_STEPS: 8
  CRITERION: 'ce'
  REDUCE_ZERO_LABEL: True
